GET {{url}}/products

###
GET {{url}}/products/a1c38af4-d208-4adb-943c-fbd9d9b4fdfe

### Non existing id
GET {{url}}/products/00000000-0000-0000-0000-000000000000

###
POST {{url}}/products
Content-Type: application/json;

{
  "title": "title",
  "description": "description",
  "price": 1000,
  "count": 0
}
